#!/usr/bin/env bash
T=$(dirname $0)
if [ ${T:0:1} != "/" ]; then
   T=$PWD/$T
fi

dollar="$"
function assign() {
	 if eval [ X"$dollar$1" == X ]; then
	    if [ -d "$2" ]; then
	       eval export $1="$2"
	    else
	       eval export $1="$3"
	    fi
	 fi
}

SYSTEM=$(uname)
if [ $SYSTEM == "Linux" ]; then
    export LD_LIBRARY_PATH=$T/viewer/bin
    export VIMAGE=eog
    export VEDITOR=atom
    assign "VMODELS"   /assig/grau-g/models   $T/models
    assign "VTEXTURES" /assig/grau-g/Textures $T/Textures
    assign "VTESTS"    /assig/grau-g/tests    $T/tests
    export LC_NUMERIC="C"
    export VPLUGINS="libnavigatedefault.so;librenderdefault.so;libdrawvbong.so;libpluginloader.so"
elif [ $SYSTEM == "Darwin" ]; then
    export LD_LIBRARY_PATH=$T/viewer/bin
    assign "VMODELS"   /assig/grau-g/models   $T/models
    assign "VTEXTURES" /assig/grau-g/Textures $T/Textures
    assign "VTESTS"    /assig/grau-g/tests    $T/tests
    export LC_NUMERIC="C"
    export VPLUGINS="libdrawvbong.dylib;libpluginloader.dylib;libnavigatedefault.dylib;librenderdefault.dylib"
fi


VGLRUN=""
VGLARGS=""
if [ X$1 == 'X-vgl' ]; then
    shift
    if [ -x /usr/bin/vglrun ]; then
	VGLRUN="/usr/bin/vglrun"
	VGLARGS=" +sync +sp "
    fi
fi

echo "Environment"
echo "VMODELS = " $VMODELS
echo "VTEXTURES = " $VTEXTURES
echo "VTESTS = " $VTESTS
echo -n "about to execute: "
if [ $SYSTEM == "Linux" ]; then
    echo ${VGLRUN} ${VGLARGS} $T/viewer/bin/viewer $@
    ${VGLRUN} ${VGLARGS} $T/viewer/bin/viewer $@
elif [ $SYSTEM == "Darwin" ]; then
    echo ${VGLRUN} ${VGLARGS} $T/viewer/bin/viewer.app/Contents/MacOS/viewer $@
    ${VGLRUN} ${VGLARGS} $T/viewer/bin/viewer.app/Contents/MacOS/viewer $@
fi

exit 0
